import { Router } from "express";
import { archiveMateriel, authorizeAttachment, confirmAttachment, createCategory, createMateriel, deleteCategory, downloadAttachment, exportMateriels, getArchivedHistory, getArchivedMateriel, getCalendar, getHistory, getMaterialReservations, getMateriel, listArchivedMateriels, listCategories, listMateriels, removeAttachment, updateCategory, updateMateriel } from "../controllers/materiel.controller.js";
import { requireSession } from "../middlewares/auth.middleware.js";

const router = Router();
router.use(requireSession);
router.get("/categories", listCategories);
router.post("/categories", createCategory);
router.patch("/categories/:id", updateCategory);
router.delete("/categories/:id", deleteCategory);
router.get("/archives", listArchivedMateriels);
router.get("/archives/:id", getArchivedMateriel);
router.get("/archives/:id/historique", getArchivedHistory);
router.get("/export", exportMateriels);
router.get("/calendrier", getCalendar);
router.get("/", listMateriels);
router.post("/", createMateriel);
router.get("/:id", getMateriel);
router.patch("/:id", updateMateriel);
router.post("/:id/archivage", archiveMateriel);
router.get("/:id/historique", getHistory);
router.get("/:id/reservations", getMaterialReservations);
router.post("/:id/pieces-jointes/autorisation", authorizeAttachment);
router.post("/:id/pieces-jointes/:pieceId/confirmation", confirmAttachment);
router.get("/:id/pieces-jointes/:pieceId", downloadAttachment);
router.delete("/:id/pieces-jointes/:pieceId", removeAttachment);
export default router;
